/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package diehard.sandbox;

public final class R {
    public static final class anim {
        public static final int push_left_in=0x7f040000;
        public static final int push_left_out=0x7f040001;
        public static final int push_up_in=0x7f040002;
        public static final int push_up_out=0x7f040003;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int solid_aqua=0x7f060007;
        public static final int solid_black=0x7f060000;
        public static final int solid_blue=0x7f06000a;
        public static final int solid_fuchsia=0x7f060008;
        public static final int solid_gray=0x7f060003;
        public static final int solid_graydark=0x7f060002;
        public static final int solid_green=0x7f06000e;
        public static final int solid_lime=0x7f06000f;
        public static final int solid_maroon=0x7f060005;
        public static final int solid_navy=0x7f06000b;
        public static final int solid_olive=0x7f06000d;
        public static final int solid_purple=0x7f060009;
        public static final int solid_red=0x7f060006;
        public static final int solid_silver=0x7f060004;
        public static final int solid_teal=0x7f06000c;
        public static final int solid_white=0x7f060001;
        public static final int solid_yellow=0x7f060010;
    }
    public static final class drawable {
        public static final int ball_tileset=0x7f020000;
        public static final int black=0x7f020003;
        public static final int blue=0x7f020005;
        public static final int green=0x7f020006;
        public static final int icon=0x7f020001;
        public static final int pong_tileset=0x7f020002;
        public static final int red=0x7f020004;
        public static final int translucent_background=0x7f020008;
        public static final int transparent_background=0x7f020009;
        public static final int yellow=0x7f020007;
    }
    public static final class id {
        public static final int console_container=0x7f070000;
        public static final int console_controlpanel=0x7f070001;
        public static final int console_execute=0x7f070003;
        public static final int console_input=0x7f070002;
        public static final int console_output=0x7f070004;
        public static final int introduction=0x7f070005;
        public static final int pong=0x7f070006;
        public static final int status=0x7f070007;
        public static final int text=0x7f070008;
    }
    public static final class layout {
        public static final int console=0x7f030000;
        public static final int main=0x7f030001;
        public static final int pong=0x7f030002;
        public static final int translucent_background=0x7f030003;
    }
    public static final class string {
        public static final int app_name1=0x7f050000;
        public static final int app_name2=0x7f050001;
        public static final int app_name3=0x7f050002;
        public static final int author=0x7f050004;
        public static final int btn_console_execute=0x7f050006;
        public static final int contextmenu_console=0x7f050005;
        public static final int state_pause=0x7f050008;
        public static final int state_ready=0x7f050007;
        public static final int vendor=0x7f050003;
    }
}
